name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SFTP_PRIVATE_KEY }}

      - name: Upload files via SFTP
        run: |
          sftp -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa root@96.30.198.245 <<EOF
          mkdir -p /root/myapp
          cd /root/myapp
          put -r ./*
          bye
          EOF
